ktor {
  deployment {
    port = 8089
  }
  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}

jwt.secret = "586E3272357538782F413F4428472B4B6250655368566B597033733676397924"
jwt.issuer = "com.example"
jwt.audience = "vetapp-users"
jwt.expiresInMs = 600000