name: Deploy Ktor App to EC2

on:
  push:
    branches:
      - dev-erick

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout código fuente
        uses: actions/checkout@v4

      - name: 🔐 Crear archivo .env
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: 🐳 Construir imagen Docker
        run: docker build -t ktor-app .

      - name: 📦 Guardar imagen Docker
        run: docker save ktor-app | gzip > ktor-app.tar.gz

      - name: 📡 Preparar entorno en EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER_FRONT }}
          key: ${{ secrets.EC2_SSH_KEY_FRONT }}
          port: 22
          script: |
            echo "🔧 Instalando Docker si no está presente..."
            if ! command -v docker &> /dev/null; then
              sudo apt update -y
              sudo apt install -y docker.io
              sudo systemctl start docker
            fi

            echo "🧹 Limpiando contenedor e imagen anteriores..."
            sudo docker stop ktor-app || true
            sudo docker rm ktor-app || true
            rm -f ~/ktor-app.tar.gz
            rm -f ~/.env

      - name: Subir archivos a EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER_FRONT }}
          key: ${{ secrets.EC2_SSH_KEY_FRONT }}
          port: 22
          source: ktor-app.tar.gz
          target: /home/${{ secrets.EC2_USER_FRONT }}/
          timeout: 30s
          command_timeout: 10m


      - name: Crear y ejecutar contenedor en EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~
            echo "${{ secrets.GEMINI_API_KEY }}" > .env
            echo "DB_URL=${{ secrets.DB_URL }}" >> .env
            echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            
            echo "📦 Cargando imagen Docker..."
            sudo docker load < ktor-app.tar.gz
            
            echo "🚀 Ejecutando contenedor..."
            sudo docker rm -f ktor-app || true
            sudo docker run -d --name ktor-app --env-file .env -p 8089:8089 ktor-app

